spring.application.name=meetmates

# en dev sans docker 

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false

spring.sql.init.mode=never

UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.CharSet=utf8mb4

LOGGING
logging.level.org.springframework.security=INFO
logging.level.com.example.meetmates=INFO
logging.level.org.springframework.web.filter=INFO

UPLOAD LIMITS
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

THYMELEAF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

app.frontend.url=${APP_FRONTEND_URL}

app.jwtSecret=${APP_JWT_SECRET}
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=604800000

MAILING
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
app.mail.from=${APP_MAIL_FROM}