spring.application.name=meetmates

FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

JPA / HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=false

spring.sql.init.mode=never

UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=utf8mb4
spring.jpa.properties.hibernate.connection.CharSet=utf8mb4

LOGGING
logging.level.org.springframework.security=INFO
logging.level.com.example.meetmates=INFO
logging.level.org.springframework.web.filter=INFO

UPLOAD LIMITS
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

THYMELEAF
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false

app.frontend.url=${APP_FRONTEND_URL:https://meetmates-1.onrender.com}
server.port=${PORT:8080}

app.jwtSecret=${APP_JWT_SECRET}
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=604800000

MAILING
resend.api.key=${RESEND_API_KEY:  String method = request.getMethod();}

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_batch_fetch_size=20

app.cookie.secure=true
app.cookie.same-site=None

resend.api.key=test-key
