spring.config.activate.on-profile=prod

# PostgreSQL (Render)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

# Frontend
app.frontend.url=${APP_FRONTEND_URL:https://meetmates-1.onrender.com}
server.port=${PORT}
# JWT
app.jwtSecret=${APP_JWT_SECRET}
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=604800000

# Mail (sécurisé)
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=${APP_MAIL_FROM}

app.cookie.secure=true
app.cookie.same-site=None
